[package]
name = "rusty_ga"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.32.1"
gl = "0.14.0"
regex = "1.11.1"